{
  imports = [
    ./application.nix
    ./asus.nix
    ./bluetooth.nix
    ./boot.nix
    ./desktops.nix
    ./env.nix
    ./nm.nix
    ./nvidia_graphics.nix
    ./sound.nix
    ./tablet.nix
    ./tailscale.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    ./zram.nix
  ];
}
